package com.giftedcat.uploadhelp.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.giftedcat.uploadhelp.db.Attendance;

import com.giftedcat.uploadhelp.dao.AttendanceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attendanceDaoConfig;

    private final AttendanceDao attendanceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attendanceDaoConfig = daoConfigMap.get(AttendanceDao.class).clone();
        attendanceDaoConfig.initIdentityScope(type);

        attendanceDao = new AttendanceDao(attendanceDaoConfig, this);

        registerDao(Attendance.class, attendanceDao);
    }
    
    public void clear() {
        attendanceDaoConfig.clearIdentityScope();
    }

    public AttendanceDao getAttendanceDao() {
        return attendanceDao;
    }

}
